In [30]:
from pandas import DataFrame,read_csv,read_excel,merge,melt,pivot_table
import numpy
from matplotlib import pyplot as plt
import seaborn as sb
import sys
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from factor_analyzer.factor_analyzer import calculate_kmo

In [31]:
plt.rcParams["font.family"] = 'AppleGothic' if sys.platform == 'darwin' else 'Malgun Gothic'
plt.rcParams["font.size"] = 12
plt.rcParams["figure.figsize"] = (8, 5)
plt.rcParams["axes.unicode_minus"] = False

In [32]:
# origin=read_excel('행정동병합테스트22.xlsx')
origin=read_excel('행정동병합테스트22(개발제한행정동제외).xlsx')
origin2=read_excel('여가생활지수1.xlsx')
origin3=read_excel('사회적약자지수1.xlsx')
origin4=read_excel('접근성지수1.xlsx')
origin5=read_excel('그린지수1.xlsx')
origin.head(1)

,Unnamed: 0,시도명,시군구코드,시군구명,행정동코드,행정동코드_수정,읍면동명,생성일자,말소일자,지하철역_수,...,노인인구(65세이상),장애인_인구,세대당공원면적,보육시설수,세대당공원면적minmax,수변점수,행정동별버스정류장수,행정동별유통업체수,공공자전거대여소수,인구밀도
0,0,서울특별시,11110,종로구,1111051500,11110515,청운효자동,20081101,0,0,...,2154,437,337.55,4,0.352898,0,32,0,3,4552.529183

In [33]:
origin.head(2)

,Unnamed: 0,시도명,시군구코드,시군구명,행정동코드,행정동코드_수정,읍면동명,생성일자,말소일자,지하철역_수,...,노인인구(65세이상),장애인_인구,세대당공원면적,보육시설수,세대당공원면적minmax,수변점수,행정동별버스정류장수,행정동별유통업체수,공공자전거대여소수,인구밀도
0,0,서울특별시,11110,종로구,1111051500,11110515,청운효자동,20081101,0,0,...,2154,437,337.55,4,0.352898,0,32,0,3,4552.529183
1,1,서울특별시,11110,종로구,1111053000,11110530,사직동,19880423,0,2,...,1808,267,60.79,0,0.063554,0,27,0,12,7611.382114

In [34]:
origin2_2=origin2.filter(['읍면동명','여가생활지수minmax'])
origin2_2.head(2)

    읍면동명  여가생활지수minmax
0  청운효자동      0.062205
1    사직동      0.038557

In [35]:
origin3_3=origin3.filter(['읍면동명','사회적약자_지원_인프라_밀집도minmax'])
origin3_3.head(2)

    읍면동명  사회적약자_지원_인프라_밀집도minmax
0  청운효자동                0.166880
1    사직동                0.044126

In [36]:
origin4_4=origin4.filter(['읍면동명','접근성지수minmax'])
origin4_4.head(2)

    읍면동명  접근성지수minmax
0  청운효자동     0.133927
1    사직동     0.184545

In [37]:
origin5_5=origin5.filter(['읍면동명','그린지수minmax'])
origin5_5.head(2)

    읍면동명  그린지수minmax
0  청운효자동    0.212495
1    사직동    0.038269

In [38]:
tmp=merge(origin,origin2_2,how='left')
tmp.head()

,Unnamed: 0,시도명,시군구코드,시군구명,행정동코드,행정동코드_수정,읍면동명,생성일자,말소일자,지하철역_수,...,장애인_인구,세대당공원면적,보육시설수,세대당공원면적minmax,수변점수,행정동별버스정류장수,행정동별유통업체수,공공자전거대여소수,인구밀도,여가생활지수minmax
0,0,서울특별시,11110,종로구,1111051500,11110515,청운효자동,20081101,0,0,...,437,337.55,4,0.352898,0,32,0,3,4552.529183,0.062205
1,1,서울특별시,11110,종로구,1111053000,11110530,사직동,19880423,0,2,...,267,60.79,0,0.063554,0,27,0,12,7611.382114,0.038557
2,2,서울특별시,11110,종로구,1111054000,11110540,삼청동,19880423,0,0,...,110,956.51,3,1.000000,0,16,0,5,1728.859060,0.182711
3,3,서울특별시,11110,종로구,1111055000,11110550,부암동,19880423,0,0,...,311,0.00,3,0.000000,10,34,0,5,4130.837004,0.038414
4,4,서울특별시,11110,종로구,1111056000,11110560,평창동,19880423,0,0,...,491,1.14,3,0.001192,10,54,0,5,1990.755355,0.107249

In [39]:
tmp1=merge(tmp,origin3_3,how='left')
tmp1

,Unnamed: 0,시도명,시군구코드,시군구명,행정동코드,행정동코드_수정,읍면동명,생성일자,말소일자,지하철역_수,...,세대당공원면적,보육시설수,세대당공원면적minmax,수변점수,행정동별버스정류장수,행정동별유통업체수,공공자전거대여소수,인구밀도,여가생활지수minmax,사회적약자_지원_인프라_밀집도minmax
0,0,서울특별시,11110,종로구,1111051500,11110515,청운효자동,20081101,0,0,...,337.55,4,0.352898,0,32,0,3,4552.529183,0.062205,0.166880
1,1,서울특별시,11110,종로구,1111053000,11110530,사직동,19880423,0,2,...,60.79,0,0.063554,0,27,0,12,7611.382114,0.038557,0.044126
2,2,서울특별시,11110,종로구,1111054000,11110540,삼청동,19880423,0,0,...,956.51,3,1.000000,0,16,0,5,1728.859060,0.182711,0.118277
3,3,서울특별시,11110,종로구,1111055000,11110550,부암동,19880423,0,0,...,0.00,3,0.000000,10,34,0,5,4130.837004,0.038414,0.144440
4,4,서울특별시,11110,종로구,1111056000,11110560,평창동,19880423,0,0,...,1.14,3,0.001192,10,54,0,5,1990.755355,0.107249,0.658702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,421,서울특별시,11740,강동구,1174065000,11740650,성내제2동,19880423,0,3,...,0.18,9,0.000188,4,18,1,5,34780.597015,0.002084,0.027923
402,422,서울특별시,11740,강동구,1174066000,11740660,성내제3동,19880423,0,1,...,0.35,11,0.000366,9,15,1,6,32228.169014,0.001992,0.037726
403,423,서울특별시,11740,강동구,1174068500,11740685,길동,20080707,0,1,...,4.11,17,0.004297,0,36,2,7,28038.509317,0.005104,0.082530
404,424,서울특별시,11740,강동구,1174069000,11740690,둔촌제1동,19880423,0,1,...,0.00,0,0.000000,7,9,0,4,76.086957,0.000000,0.708442
405,425,서울특별시,11740,강동구,1174070000,11740700,둔촌제2동,19880423,0,1,...,58.91,15,0.061588,0,30,0,9,15492.948718,0.002969,0.120707

In [40]:
tmp2=merge(tmp1,origin4_4,how='left')
tmp2.head()

,Unnamed: 0,시도명,시군구코드,시군구명,행정동코드,행정동코드_수정,읍면동명,생성일자,말소일자,지하철역_수,...,보육시설수,세대당공원면적minmax,수변점수,행정동별버스정류장수,행정동별유통업체수,공공자전거대여소수,인구밀도,여가생활지수minmax,사회적약자_지원_인프라_밀집도minmax,접근성지수minmax
0,0,서울특별시,11110,종로구,1111051500,11110515,청운효자동,20081101,0,0,...,4,0.352898,0,32,0,3,4552.529183,0.062205,0.166880,0.133927
1,1,서울특별시,11110,종로구,1111053000,11110530,사직동,19880423,0,2,...,0,0.063554,0,27,0,12,7611.382114,0.038557,0.044126,0.184545
2,2,서울특별시,11110,종로구,1111054000,11110540,삼청동,19880423,0,0,...,3,1.000000,0,16,0,5,1728.859060,0.182711,0.118277,0.233276
3,3,서울특별시,11110,종로구,1111055000,11110550,부암동,19880423,0,0,...,3,0.000000,10,34,0,5,4130.837004,0.038414,0.144440,0.162233
4,4,서울특별시,11110,종로구,1111056000,11110560,평창동,19880423,0,0,...,3,0.001192,10,54,0,5,1990.755355,0.107249,0.658702,0.560716

In [41]:
tmp3=merge(tmp2,origin5_5,how='left')
tmp3.head()

,Unnamed: 0,시도명,시군구코드,시군구명,행정동코드,행정동코드_수정,읍면동명,생성일자,말소일자,지하철역_수,...,세대당공원면적minmax,수변점수,행정동별버스정류장수,행정동별유통업체수,공공자전거대여소수,인구밀도,여가생활지수minmax,사회적약자_지원_인프라_밀집도minmax,접근성지수minmax,그린지수minmax
0,0,서울특별시,11110,종로구,1111051500,11110515,청운효자동,20081101,0,0,...,0.352898,0,32,0,3,4552.529183,0.062205,0.166880,0.133927,0.212495
1,1,서울특별시,11110,종로구,1111053000,11110530,사직동,19880423,0,2,...,0.063554,0,27,0,12,7611.382114,0.038557,0.044126,0.184545,0.038269
2,2,서울특별시,11110,종로구,1111054000,11110540,삼청동,19880423,0,0,...,1.000000,0,16,0,5,1728.859060,0.182711,0.118277,0.233276,0.602143
3,3,서울특별시,11110,종로구,1111055000,11110550,부암동,19880423,0,0,...,0.000000,10,34,0,5,4130.837004,0.038414,0.144440,0.162233,0.602143
4,4,서울특별시,11110,종로구,1111056000,11110560,평창동,19880423,0,0,...,0.001192,10,54,0,5,1990.755355,0.107249,0.658702,0.560716,0.602861

In [42]:
tmp3.columns

Index(['Unnamed: 0', '시도명', '시군구코드', '시군구명', '행정동코드', '행정동코드_수정', '읍면동명',
       '생성일자', '말소일자', '지하철역_수', '의료기관_수', '사회복지시설_수', '계(명)', '면적 (k㎡)',
       '구성비 (%)', '행정동별_공원수', '공공체육시설_수', '문화시설_수', '학교_수', '사업체_수',
       '개소 (공영+민영)', '면수 (공영+민영)', '하천및한강여부', '아동인구(0~9세)', '노인인구(65세이상)',
       '장애인_인구', '세대당공원면적', '보육시설수', '세대당공원면적minmax', '수변점수', '행정동별버스정류장수',
       '행정동별유통업체수', '공공자전거대여소수', '인구밀도', '여가생활지수minmax',
       '사회적약자_지원_인프라_밀집도minmax', '접근성지수minmax', '그린지수minmax'],
      dtype='object')

In [43]:
tmp3.to_excel('행정동병합최종.xlsx',index=False)